### PR TITLE
Handle internal and external links

### PR DESCRIPTION
**Pull request by io7m**
This change makes a number of improvements to the existing code:

  * Links are now handled. Internal links will generate a new
    OpenLink command, which internally either tries to open
    a chapter with the given href, or publishes an event that
    causes the fragment to try to open an external web browser.

  * Starts the migration away from runOnUIThread() towards using
    a UnicastWorkSubject that is guaranteed to observe events
    only on the Android UI thread. This fixes a number of lifecycle
    issues.

### CODE REVIEW

**Review by qnga — COMMENTED** [review]
- I'm not sure I understand the rationale behind separating SR2ViewModelBookEvent and SR2Event.
- Looking at the code, event lifecycles seems fine.
- The DemoActivity doesn't resist orientation changes though, so it's difficult to test them. It's not possible to load a book after rotating the device, and doing it while a book has already been opened leads to a crash because the factory for SR2ReaderFragment is set far too late.
- External link handling seems fine.
- I couldn't really test internal links because I don't have an EPUB that I can trust and contains some of them. Do you have one to share with me?

**Comment by io7m** [comment]
> I'm not sure I understand the rationale behind separating SR2ViewModelBookEvent and SR2Event.

I didn't want to make those events part of the "public" controller API, particularly as they're published outside of the controller's lifecycle. There'd be a chicken and egg problem where you'd need to get a reference to the controller in order to subscribe to the event stream that told you why you couldn't have a controller instance. :slightly_smiling_face: 

They're not really of interest to anything other than the fragment implementation, so they're kept "private" for now. We can revisit this later if necessary.

> Looking at the code, event lifecycles seems fine.

Phew!

> The DemoActivity doesn't resist orientation changes though, so it's difficult to test them. It's not possible to load a book after rotating the device, and doing it while a book has already been opened leads to a crash because the factory for SR2ReaderFragment is set far too late.

Yes, this was somewhat thrown together for testing early last year and could do with cleaning up. Making the button to select a book be part of a fragment that's swapped out when the reader is loaded would help.

> External link handling seems fine.

That's the easy part. :slightly_smiling_face: 

> I couldn't really test internal links because I don't have an EPUB that I can trust and contains some of them. Do you have one to share with me?

I've attached "Great Expectations". That has a few links in the cover matter that links to license information at the end of the book. Look for the Unlicense link.

[charles-dickens_great-expectations.epub.gz](https://github.com/NYPL-Simplified/Simplified-R2-Android/files/6649979/charles-dickens_great-expectations.epub.gz)

(GitHub made me gzip it before I could upload it)

**Comment by qnga** [comment]
Ok! At least in the demo, the last reading position still seems not to be saved after navigating through internal links.
It might be because of the following error:
`2021-06-15 09:06:01.838 7011-7011/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onPageFinished: http://127.0.0.1:42501/5b08b3198c4022e0416397fc635edab8/epub/text/uncopyright.xhtml
2021-06-15 09:06:01.839 7011-7011/org.librarysimplified.r2.demo E/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onPageFinished: http://127.0.0.1:42501/5b08b3198c4022e0416397fc635edab8/epub/text/uncopyright.xhtml failed with 1 errors
2021-06-15 09:06:01.839 7011-7011/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onPageFinished: completed future
2021-06-15 09:06:01.845 7011-9103/org.librarysimplified.r2.demo E/org.librarysimplified.r2.vanilla.internal.SR2WebViewConnection: [e744826e-2d23-4748-b1a1-3985480d4e90]: timed out waiting for the web view to complete: java.util.concurrent.ExecutionException: org.librarysimplified.r2.vanilla.internal.SR2WebViewLoadException: Failed to load http://127.0.0.1:42501/5b08b3198c4022e0416397fc635edab8/epub/text/uncopyright.xhtml
    	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:528) ~[na:0.0]
    	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:425) ~[na:0.0]
    	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:92) ~[na:0.0]
    	at org.librarysimplified.r2.vanilla.internal.SR2WebViewConnection.waitOrFail(SR2WebViewConnection.kt:110) ~[na:0.0]
    	at org.librarysimplified.r2.vanilla.internal.SR2WebViewConnection.access$waitOrFail(SR2WebViewConnection.kt:20) ~[na:0.0]
    	at org.librarysimplified.r2.vanilla.internal.SR2WebViewConnection$openURL$1.run(SR2WebViewConnection.kt:94) ~[na:0.0]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[na:0.0]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[na:0.0]
    	at java.lang.Thread.run(Thread.java:919) ~[na:0.0]
    Caused by: org.librarysimplified.r2.vanilla.internal.SR2WebViewLoadException: Failed to load http://127.0.0.1:42501/5b08b3198c4022e0416397fc635edab8/epub/text/uncopyright.xhtml
    	at org.librarysimplified.r2.vanilla.internal.SR2WebViewClient.onPageFinished(SR2WebViewClient.kt:99) ~[na:0.0]
    	at O7.b(PG:2) ~[na:na]
    	at Do.handleMessage(PG:65) ~[na:na]
    	at android.os.Handler.dispatchMessage(Handler.java:107) ~[na:0.0]
    	at android.os.Looper.loop(Looper.java:238) ~[na:0.0]
    	at android.app.ActivityThread.main(ActivityThread.java:7864) ~[na:0.0]
    	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) ~[na:0.0]
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:998) ~[na:0.0]
2021-06-15 09:06:01.846 7011-7895/org.librarysimplified.r2.demo E/org.librarysimplified.r2.vanilla.internal.SR2Controller: SR2CommandSubmission(id=be11e2d6-51d8-442f-87f7-a03e43130b0d, submitted=2021-06-15T09:06:01.473+02:00, command=OpenChapter(locator=SR2LocatorPercent(chapterHref=/epub/text/uncopyright.xhtml, chapterProgress=0.0))): org.librarysimplified.r2.vanilla.internal.SR2WebViewLoadException: Failed to load http://127.0.0.1:42501/5b08b3198c4022e0416397fc635edab8/epub/text/uncopyright.xhtml
    	at org.librarysimplified.r2.vanilla.internal.SR2WebViewClient.onPageFinished(SR2WebViewClient.kt:99) ~[na:0.0]
    	at O7.b(PG:2) ~[na:na]
    	at Do.handleMessage(PG:65) ~[na:na]
    	at android.os.Handler.dispatchMessage(Handler.java:107) ~[na:0.0]
    	at android.os.Looper.loop(Looper.java:238) ~[na:0.0]
    	at android.app.ActivityThread.main(ActivityThread.java:7864) ~[na:0.0]
    	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) ~[na:0.0]
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:998) ~[na:0.0]
2021-06-15 09:06:01.846 7011-7895/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2Controller: event: SR2CommandExecutionFailed(command=OpenChapter(locator=SR2LocatorPercent(chapterHref=/epub/text/uncopyright.xhtml, chapterProgress=0.0)), exception=org.librarysimplified.r2.vanilla.internal.SR2WebViewLoadException: Failed to load http://127.0.0.1:42501/5b08b3198c4022e0416397fc635edab8/epub/text/uncopyright.xhtml)
`
The right page shows up though...

**Comment by io7m** [comment]
Hm, I can't reproduce that one. This is what I get when I click the Uncopyright link:

```
2021-06-15 08:37:19.356 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: shouldOverrideUrlLoading: http://127.0.0.1:36752/91daf65b4ad722dcea44de4f16dd4bb5/epub/text/uncopyright.xhtml
2021-06-15 08:37:19.361 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2Controller: submitCommand: SR2CommandSubmission(id=605641d8-fcbb-4720-a1b2-c0e5c278f4a1, submitted=2021-06-15T09:37:19.358+01:00, command=OpenLink(link=http://127.0.0.1:36752/91daf65b4ad722dcea44de4f16dd4bb5/epub/text/uncopyright.xhtml))
2021-06-15 08:37:19.363 26122-26298/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2Controller: event: SR2CommandExecutionStarted(command=OpenLink(link=http://127.0.0.1:36752/91daf65b4ad722dcea44de4f16dd4bb5/epub/text/uncopyright.xhtml))
2021-06-15 08:37:19.366 26122-26298/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2Controller: executing SR2CommandSubmission(id=605641d8-fcbb-4720-a1b2-c0e5c278f4a1, submitted=2021-06-15T09:37:19.358+01:00, command=OpenLink(link=http://127.0.0.1:36752/91daf65b4ad722dcea44de4f16dd4bb5/epub/text/uncopyright.xhtml))
2021-06-15 08:37:19.372 26122-26298/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2Controller: submitCommand: SR2CommandSubmission(id=5ff5fbfa-d161-4f47-a007-9f6e6b6520cc, submitted=2021-06-15T09:37:19.370+01:00, command=OpenChapter(locator=SR2LocatorPercent(chapterHref=/epub/text/uncopyright.xhtml, chapterProgress=0.0)))
2021-06-15 08:37:19.377 26122-26298/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2Controller: event: SR2CommandExecutionSucceeded(command=OpenLink(link=http://127.0.0.1:36752/91daf65b4ad722dcea44de4f16dd4bb5/epub/text/uncopyright.xhtml))
2021-06-15 08:37:19.383 26122-26298/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2Controller: event: SR2CommandExecutionStarted(command=OpenChapter(locator=SR2LocatorPercent(chapterHref=/epub/text/uncopyright.xhtml, chapterProgress=0.0)))
2021-06-15 08:37:19.388 26122-26298/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2Controller: executing SR2CommandSubmission(id=5ff5fbfa-d161-4f47-a007-9f6e6b6520cc, submitted=2021-06-15T09:37:19.370+01:00, command=OpenChapter(locator=SR2LocatorPercent(chapterHref=/epub/text/uncopyright.xhtml, chapterProgress=0.0)))
2021-06-15 08:37:19.391 26122-26298/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2Controller: event: SR2CommandExecutionRunningLong(command=OpenChapter(locator=SR2LocatorPercent(chapterHref=/epub/text/uncopyright.xhtml, chapterProgress=0.0)))
2021-06-15 08:37:19.396 26122-26298/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2Controller: openChapterForLocator: http://127.0.0.1:36752/91daf65b4ad722dcea44de4f16dd4bb5/epub/text/uncopyright.xhtml
2021-06-15 08:37:19.399 26122-26301/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewConnection: [79b6a28c-3395-40d1-993a-80856270f103]: openURL http://127.0.0.1:36752/91daf65b4ad722dcea44de4f16dd4bb5/epub/text/uncopyright.xhtml
2021-06-15 08:37:19.401 26122-26301/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewConnection: [79b6a28c-3395-40d1-993a-80856270f103]: waiting for request to complete
2021-06-15 08:37:19.408 26122-26122/org.librarysimplified.r2.demo E/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onReceivedError: http://127.0.0.1:36752/favicon.ico: -1 There was a network error.
2021-06-15 08:37:19.444 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onLoadResource: http://127.0.0.1:36752/91daf65b4ad722dcea44de4f16dd4bb5/epub/text/uncopyright.xhtml
2021-06-15 08:37:19.598 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onLoadResource: http://127.0.0.1:36752/assets/readium-css/ReadiumCSS-before.css
2021-06-15 08:37:19.606 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onLoadResource: http://127.0.0.1:36752/91daf65b4ad722dcea44de4f16dd4bb5/epub/css/core.css
2021-06-15 08:37:19.608 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onLoadResource: http://127.0.0.1:36752/91daf65b4ad722dcea44de4f16dd4bb5/epub/css/local.css
2021-06-15 08:37:19.617 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onLoadResource: http://127.0.0.1:36752/assets/readium-css/ReadiumCSS-after.css
2021-06-15 08:37:19.624 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onLoadResource: http://127.0.0.1:36752/assets/scripts/gestures.js
2021-06-15 08:37:19.773 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onLoadResource: http://127.0.0.1:36752/assets/scripts/utils.js
2021-06-15 08:37:19.871 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onLoadResource: http://127.0.0.1:36752/assets/scripts/crypto-sha256.js
2021-06-15 08:37:19.965 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onLoadResource: http://127.0.0.1:36752/assets/scripts/highlight.js
2021-06-15 08:37:20.066 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onLoadResource: https://fonts.googleapis.com/css?family=PT+Serif|Roboto|Source+Sans+Pro|Vollkorn
2021-06-15 08:37:20.178 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onPageFinished: http://127.0.0.1:36752/91daf65b4ad722dcea44de4f16dd4bb5/epub/text/uncopyright.xhtml
2021-06-15 08:37:20.179 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onPageFinished: http://127.0.0.1:36752/91daf65b4ad722dcea44de4f16dd4bb5/epub/text/uncopyright.xhtml succeeded
2021-06-15 08:37:20.180 26122-26301/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewConnection: [79b6a28c-3395-40d1-993a-80856270f103]: request completed
2021-06-15 08:37:20.181 26122-26301/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewConnection: [fb8c54a0-134e-46e2-8884-66b3c032f36a] executeJS
2021-06-15 08:37:20.182 26122-26122/org.librarysimplified.r2.demo D/org.librarysimplified.r2.vanilla.internal.SR2WebViewClient: onPageFinished: completed future
```

device-2021-06-15-083854

**Comment by io7m** [comment]
Any ideas as to why the future is timing out on your device? What Android API level is this?

**Comment by qnga** [comment]
Trying to debug this, here is what I get:
- Logs are misleading [there](https://github.com/NYPL-Simplified/Simplified-R2-Android/blob/0771bc2e9fdaad0fc08ed68f37d6c10a5681c82f/org.librarysimplified.r2.vanilla/src/main/java/org/librarysimplified/r2/vanilla/internal/SR2WebViewConnection.kt#L111). The future never timed out, a `SR2WebViewLoadException` was raised.
- The stack trace points to [there](https://github.com/NYPL-Simplified/Simplified-R2-Android/blob/0771bc2e9fdaad0fc08ed68f37d6c10a5681c82f/org.librarysimplified.r2.vanilla/src/main/java/org/librarysimplified/r2/vanilla/internal/SR2WebViewClient.kt#L78). The exception seems to be raised only because loading `favicon.ico` failed.

Let me know if this is not enough for you to track down the issue.

**Comment by io7m** [comment]
Ah! Thanks, yes, that should do it. Unsure why that `catch` clause was so broad... :thinking:

**Comment by io7m** [comment]
I just pushed a commit that adjusts that `catch` clause, and also actually serves a favicon when asked rather than an empty response. Weird that it's not a fatal error on my device... Perhaps some `WebViews` are stricter than others.

**Review by qnga — APPROVED** [review]
Even on my device, the bug occurred "randomly". It looks fine now!

**Pull request merged**
