### PR TITLE
SMA-237: Update Publisher Toggle UX

### PR DESCRIPTION
**Pull request by qnga**
Remove the publisher default switch and present publisher default as a font instead.

### CODE REVIEW

**Review by io7m — APPROVED** [review]
Looks good to me!

Is there an application-side part to this? Looks like there are some new constants that people might want saved to their preferences in the app.

device-2021-09-01-164309

**Comment by qnga** [comment]
Err.. no. What constants?

**Comment by io7m** [comment]
The option to enable/disable publisher defaults, for one.

**Comment by io7m** [comment]
Guess that was the only one, actually. The others are internal.

**Comment by qnga** [comment]
That's not a new option. I've just changed the UI. Selecting `Pub` enables publisher defaults, and selecting another tab disables them at the same time as it selects a new font.

**Pull request merged**
